import { defineConfig } from 'vite';
import { fileURLToPath } from 'node:url';
import { readdirSync, existsSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';
import type { Plugin } from 'vite';

/**
 * Exposes the list of PNGs in public/textures/overrides as `virtual:texture-overrides`
 * (block textures by file name, item sprites as `item/<name>.png`).
 */
function textureOverrides(): Plugin {
  const id = 'virtual:texture-overrides';
  const dir = fileURLToPath(new URL('./public/textures/overrides', import.meta.url));
  return {
    name: 'texture-overrides',
    resolveId: (s) => (s === id ? '\0' + id : null),
    load(s) {
      if (s !== '\0' + id) return null;
      const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.png')) : [];
      const itemDir = `${dir}/item`;
      if (existsSync(itemDir)) for (const f of readdirSync(itemDir)) if (f.endsWith('.png')) files.push(`item/${f}`);
      return `export default ${JSON.stringify(files)};`;
    },
    configureServer(server) {
      server.watcher.add(dir);
      server.watcher.on('all', (_e, file) => {
        if (file.startsWith(dir)) {
          const m = server.moduleGraph.getModuleById('\0' + id);
          if (m) server.moduleGraph.invalidateModule(m);
        }
      });
    },
  };
}

/**
 * Offline play: after a build, writes dist/sw.js, a service worker that caches every file of the
 * build on the first visit and serves them cache-first, so the game (and offline LAN pairing) runs
 * with no internet. The cache name changes with the build; a new version takes over once every
 * game tab has been closed, so a running game never loses its files mid-session.
 */
function offlineCache(): Plugin {
  let outDir = '';
  return {
    name: 'offline-cache',
    apply: 'build',
    configResolved(c) {
      outDir = c.build.outDir.startsWith('/') ? c.build.outDir : join(c.root, c.build.outDir);
    },
    closeBundle() {
      const files: string[] = [];
      const hash = createHash('sha1');
      const walk = (dir: string) => {
        for (const name of readdirSync(dir).sort()) {
          const full = join(dir, name);
          const st = statSync(full);
          if (st.isDirectory()) walk(full);
          else if (!name.endsWith('.map') && name !== 'sw.js') {
            const rel = relative(outDir, full).split('\\').join('/');
            files.push(`./${rel}`);
            hash.update(`${rel}:${st.size};`);
          }
        }
      };
      walk(outDir);
      const version = hash.digest('hex').slice(0, 12);
      writeFileSync(join(outDir, 'sw.js'), `// generated by the offline-cache plugin in vite.config.ts
const CACHE = 'blockcraft-${version}';
const FILES = ${JSON.stringify(['./', ...files])};
self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    for (let i = 0; i < FILES.length; i += 40) await cache.addAll(FILES.slice(i, i + 40));
  })());
});
self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('blockcraft-') && k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = (await cache.match(req, { ignoreSearch: true })) || (req.mode === 'navigate' ? await cache.match('./') : undefined);
    if (hit) return hit;
    try {
      return await fetch(req);
    } catch {
      return new Response('Blockcraft is offline and this file was not cached yet.', { status: 503 });
    }
  })());
});
`);
      console.log(`offline cache: ${files.length} files, version ${version}`);
    },
  };
}

export default defineConfig({
  // relative asset paths so the build runs from any folder (static hosts, the desktop app)
  base: './',
  plugins: [textureOverrides(), offlineCache()],
  resolve: {
    alias: { '@shared': fileURLToPath(new URL('../shared/src', import.meta.url)), '@server': fileURLToPath(new URL('../server/src', import.meta.url)) },
  },
  server: { port: 5173, host: true },
  worker: { format: 'es' },
  build: { target: 'es2022', sourcemap: true },
});
