/**
 * Biome generation parameters (1.16/1.17): temperature, terrain depth and scale, and surface builder.
 * Extracted from SeedFinding mc_biome_java Biomes.java (MIT, licenses/SeedFinding.txt).
 */
export interface BiomeGen {
  name: string;
  temperature: number;
  depth: number;
  scale: number;
  surface: string;
}

export const BIOME_GEN: Record<number, BiomeGen> = {
  0: { name: 'ocean', temperature: 0.5, depth: -1.0, scale: 0.1, surface: 'grass' },
  1: { name: 'plains', temperature: 0.8, depth: 0.125, scale: 0.05, surface: 'grass' },
  2: { name: 'desert', temperature: 2.0, depth: 0.125, scale: 0.05, surface: 'desert' },
  3: { name: 'mountains', temperature: 0.2, depth: 1.0, scale: 0.5, surface: 'mountain' },
  4: { name: 'forest', temperature: 0.7, depth: 0.1, scale: 0.2, surface: 'grass' },
  5: { name: 'taiga', temperature: 0.25, depth: 0.2, scale: 0.2, surface: 'grass' },
  6: { name: 'swamp', temperature: 0.8, depth: -0.2, scale: 0.1, surface: 'swamp' },
  7: { name: 'river', temperature: 0.5, depth: -0.5, scale: 0.0, surface: 'grass' },
  8: { name: 'nether_wastes', temperature: 2.0, depth: 0.1, scale: 0.2, surface: 'nether' },
  9: { name: 'the_end', temperature: 0.5, depth: 0.1, scale: 0.2, surface: 'end' },
  10: { name: 'frozen_ocean', temperature: 0.0, depth: -1.0, scale: 0.1, surface: 'frozen_ocean' },
  11: { name: 'frozen_river', temperature: 0.0, depth: -0.5, scale: 0.0, surface: 'grass' },
  12: { name: 'snowy_tundra', temperature: 0.0, depth: 0.125, scale: 0.05, surface: 'grass' },
  13: { name: 'snowy_mountains', temperature: 0.0, depth: 0.45, scale: 0.3, surface: 'grass' },
  14: { name: 'mushroom_fields', temperature: 0.9, depth: 0.2, scale: 0.3, surface: 'mycelium' },
  15: { name: 'mushroom_field_shore', temperature: 0.9, depth: 0.0, scale: 0.025, surface: 'mycelium' },
  16: { name: 'beach', temperature: 0.8, depth: 0.0, scale: 0.025, surface: 'desert' },
  17: { name: 'desert_hills', temperature: 2.0, depth: 0.45, scale: 0.3, surface: 'desert' },
  18: { name: 'wooded_hills', temperature: 0.7, depth: 0.45, scale: 0.3, surface: 'grass' },
  19: { name: 'taiga_hills', temperature: 0.25, depth: 0.45, scale: 0.3, surface: 'grass' },
  20: { name: 'mountain_edge', temperature: 0.2, depth: 0.8, scale: 0.3, surface: 'grass' },
  21: { name: 'jungle', temperature: 0.95, depth: 0.1, scale: 0.2, surface: 'grass' },
  22: { name: 'jungle_hills', temperature: 0.95, depth: 0.45, scale: 0.3, surface: 'grass' },
  23: { name: 'jungle_edge', temperature: 0.95, depth: 0.1, scale: 0.2, surface: 'grass' },
  24: { name: 'deep_ocean', temperature: 0.5, depth: -1.8, scale: 0.1, surface: 'grass' },
  25: { name: 'stone_shore', temperature: 0.2, depth: 0.1, scale: 0.8, surface: 'stone' },
  26: { name: 'snowy_beach', temperature: 0.05, depth: 0.0, scale: 0.025, surface: 'desert' },
  27: { name: 'birch_forest', temperature: 0.6, depth: 0.1, scale: 0.2, surface: 'grass' },
  28: { name: 'birch_forest_hills', temperature: 0.6, depth: 0.45, scale: 0.3, surface: 'grass' },
  29: { name: 'dark_forest', temperature: 0.7, depth: 0.1, scale: 0.2, surface: 'grass' },
  30: { name: 'snowy_taiga', temperature: -0.5, depth: 0.2, scale: 0.2, surface: 'grass' },
  31: { name: 'snowy_taiga_hills', temperature: -0.5, depth: 0.45, scale: 0.3, surface: 'grass' },
  32: { name: 'giant_tree_taiga', temperature: 0.3, depth: 0.2, scale: 0.2, surface: 'giant_tree_taiga' },
  33: { name: 'giant_tree_taiga_hills', temperature: 0.3, depth: 0.45, scale: 0.3, surface: 'giant_tree_taiga' },
  34: { name: 'wooded_mountains', temperature: 0.2, depth: 1.0, scale: 0.5, surface: 'grass' },
  35: { name: 'savanna', temperature: 1.2, depth: 0.125, scale: 0.05, surface: 'grass' },
  36: { name: 'savanna_plateau', temperature: 1.0, depth: 1.5, scale: 0.025, surface: 'grass' },
  37: { name: 'badlands', temperature: 2.0, depth: 0.1, scale: 0.2, surface: 'badlands' },
  38: { name: 'wooded_badlands_plateau', temperature: 2.0, depth: 1.5, scale: 0.025, surface: 'wooded_badlands' },
  39: { name: 'badlands_plateau', temperature: 2.0, depth: 1.5, scale: 0.025, surface: 'badlands' },
  40: { name: 'small_end_islands', temperature: 0.5, depth: 0.1, scale: 0.2, surface: 'end' },
  41: { name: 'end_midlands', temperature: 0.5, depth: 0.1, scale: 0.2, surface: 'end' },
  42: { name: 'end_highlands', temperature: 0.5, depth: 0.1, scale: 0.2, surface: 'end' },
  43: { name: 'end_barrens', temperature: 0.5, depth: 0.1, scale: 0.2, surface: 'end' },
  44: { name: 'warm_ocean', temperature: 0.5, depth: -1.0, scale: 0.1, surface: 'full_sand' },
  45: { name: 'lukewarm_ocean', temperature: 0.5, depth: -1.0, scale: 0.1, surface: 'ocean_sand' },
  46: { name: 'cold_ocean', temperature: 0.5, depth: -1.0, scale: 0.1, surface: 'grass' },
  47: { name: 'deep_warm_ocean', temperature: 0.5, depth: -1.8, scale: 0.1, surface: 'full_sand' },
  48: { name: 'deep_lukewarm_ocean', temperature: 0.5, depth: -1.8, scale: 0.1, surface: 'ocean_sand' },
  49: { name: 'deep_cold_ocean', temperature: 0.5, depth: -1.8, scale: 0.1, surface: 'grass' },
  50: { name: 'deep_frozen_ocean', temperature: 0.5, depth: -1.8, scale: 0.1, surface: 'frozen_ocean' },
  129: { name: 'sunflower_plains', temperature: 0.8, depth: 0.125, scale: 0.05, surface: 'grass' },
  130: { name: 'desert_lakes', temperature: 2.0, depth: 0.225, scale: 0.25, surface: 'desert' },
  131: { name: 'gravelly_mountains', temperature: 0.2, depth: 1.0, scale: 0.5, surface: 'gravelly_mountain' },
  132: { name: 'flower_forest', temperature: 0.7, depth: 0.1, scale: 0.4, surface: 'grass' },
  133: { name: 'taiga_mountains', temperature: 0.25, depth: 0.3, scale: 0.4, surface: 'grass' },
  134: { name: 'swamp_hills', temperature: 0.8, depth: -0.1, scale: 0.3, surface: 'swamp' },
  140: { name: 'ice_spikes', temperature: 0.0, depth: 0.425, scale: 0.45, surface: 'ice_spikes' },
  149: { name: 'modified_jungle', temperature: 0.95, depth: 0.2, scale: 0.4, surface: 'grass' },
  151: { name: 'modified_jungle_edge', temperature: 0.95, depth: 0.2, scale: 0.4, surface: 'grass' },
  155: { name: 'tall_birch_forest', temperature: 0.6, depth: 0.2, scale: 0.4, surface: 'grass' },
  156: { name: 'tall_birch_hills', temperature: 0.6, depth: 0.55, scale: 0.5, surface: 'grass' },
  157: { name: 'dark_forest_hills', temperature: 0.7, depth: 0.2, scale: 0.4, surface: 'grass' },
  158: { name: 'snowy_taiga_mountains', temperature: -0.5, depth: 0.3, scale: 0.4, surface: 'grass' },
  160: { name: 'giant_spruce_taiga', temperature: 0.25, depth: 0.2, scale: 0.2, surface: 'giant_tree_taiga' },
  161: { name: 'giant_spruce_taiga_hills', temperature: 0.25, depth: 0.2, scale: 0.2, surface: 'giant_tree_taiga' },
  162: { name: 'modified_gravelly_mountains', temperature: 0.2, depth: 1.0, scale: 0.5, surface: 'gravelly_mountain' },
  163: { name: 'shattered_savanna', temperature: 1.1, depth: 0.3625, scale: 1.225, surface: 'shattered_savanna' },
  164: { name: 'shattered_savanna_plateau', temperature: 1.0, depth: 1.05, scale: 1.212, surface: 'shattered_savanna' },
  165: { name: 'eroded_badlands', temperature: 2.0, depth: 0.1, scale: 0.2, surface: 'eroded_badlands' },
  166: { name: 'modified_wooded_badlands_plateau', temperature: 2.0, depth: 0.45, scale: 0.3, surface: 'wooded_badlands' },
  167: { name: 'modified_badlands_plateau', temperature: 2.0, depth: 0.45, scale: 0.3, surface: 'badlands' },
  168: { name: 'bamboo_jungle', temperature: 0.95, depth: 0.1, scale: 0.2, surface: 'grass' },
  169: { name: 'bamboo_jungle_hills', temperature: 0.95, depth: 0.45, scale: 0.3, surface: 'grass' },
  170: { name: 'soul_sand_valley', temperature: 2.0, depth: 0.1, scale: 0.2, surface: 'soul_sand_valley' },
  171: { name: 'crimson_forest', temperature: 2.0, depth: 0.1, scale: 0.2, surface: 'crimson_forest' },
  172: { name: 'warped_forest', temperature: 2.0, depth: 0.1, scale: 0.2, surface: 'warped_forest' },
  173: { name: 'basalt_deltas', temperature: 2.0, depth: 0.1, scale: 0.2, surface: 'basalt_deltas' },
};
