import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await b.newPage({ viewport: { width: 400, height: 300 } });
await page.goto('http://localhost:4173/?nolock=1&rd=3&scene=models&x=14.5&y=102&z=8.5&lookat=14.5,101,2.5&time=18000');
await page.waitForFunction(() => (window as any).game?.loggedIn && (window as any).game.chunks.stats().sections > 30);
await page.waitForTimeout(3000);
await page.screenshot({ path: '/tmp/claude-0/shots/p1.png' });
await page.evaluate(() => { const g = (window as any).game; g.lightmap.update = function () { const gl = g.gl; gl.bindTexture(gl.TEXTURE_2D, this.tex); gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, 16, 16, gl.RGBA, gl.UNSIGNED_BYTE, new Uint8Array(1024)); }; });
await page.waitForTimeout(1000);
await page.screenshot({ path: '/tmp/claude-0/shots/p2.png' });
await b.close();
